remote_theme: daattali/beautiful-jekyll@6.0.1
title: a blog, inrainyclouds

author: inrainyclouds

description: a site for things i do and things i like
navbar-links:
  About Me: "aboutme"
  Writeups:
   - Bandit
   - PicoCTF
  Substack: "https://humanfriendoftheplants.substack.com/"


social-network-links:
  rss: true
  twitter: #
  github: inrainyclouds

title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
post_search: true

exclude:
 - README.md
 - docs/

plugins:
 - jekyll-paginate
 - jekyll-sitemap
